version: 2
project_name: cntb
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - main: ./main.go
    binary: cntb
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -w -s -X contabo.com/cli/cntb/cmd.version={{.Tag}} -X contabo.com/cli/cntb/cmd.commit={{.Commit}} -X contabo.com/cli/cntb/cmd.date={{.Date}}
archives:
  - name_template: >-
      {{ .Binary }}_
      {{- .Tag }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
release:
  github:
    owner: contabo
    name: cntb
  draft: false
  prerelease: auto
  header: |

  footer: |